export const QUERY_KEYS = {
  DECKS: ["decks"] as const,
  DECK: (id: string) => ["decks", id] as const,
  CARDS: (deckId: string) => ["cards", deckId] as const,
  CARD: (id: string) => ["cards", "detail", id] as const,
  DUE_CARDS: ["reviews", "due"] as const,
  FOCUS_CARDS: ["reviews", "focus"] as const,
  REVIEWS: ["reviews"] as const,
  DICTIONARY: (q: string) => ["dictionary", q] as const,
  INTEGRATIONS: ["integrations"] as const,
  ANALYTICS: ["analytics"] as const,
  COVERAGE: ["coverage"] as const,
  GRAMMAR_LIBRARY: ["grammar", "library"] as const,
  WEAK_POINTS: ["analytics", "weak-points"] as const,
  MISSIONS: ["missions", "today"] as const,
};
