export const ROUTES = {
  HOME: "/",
  PRICING: "/pricing",
  DOWNLOAD: "/download",
  CHECKOUT: "/checkout",
  ONBOARDING: "/welcome",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  DECK: (id: string) => `/decks/${id}`,
  REVIEW: "/review",
  DICTIONARY: "/dictionary",
  ACCOUNT: "/account",
  INTEGRATIONS: "/settings/integrations",
} as const;
