export const ROUTES = {
  HOME: "/",
  PRICING: "/pricing",
  DOWNLOAD: "/download",
  CHECKOUT: "/checkout",
  ONBOARDING: "/welcome",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  DECK: (id: string) => `/decks/${id}`,
  REVIEW: "/review",
  ANALYTICS: "/analytics",
  JLPT: "/jlpt",
  COVERAGE: "/coverage",
  GRAMMAR: "/grammar",
  GRAMMAR_MASTERY: "/grammar/mastery",
  DICTIONARY: "/dictionary",
  ACCOUNT: "/account",
  INTEGRATIONS: "/settings/integrations",
  SETUP: "/setup",
} as const;
